# Generated by Django 4.0.3 on 2022-04-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories2_api', '0002_photo_likes_photo_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='creator',
            field=models.CharField(default='Anonymous', max_length=32),
        ),
    ]
